services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shecancode}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  leave-service:
    build:
      context: ./leavemanagementsystem
      dockerfile: Dockerfile
    container_name: leave-service
    env_file: .env
    environment:
      - DB_URL=${DB_URL:-jdbc:postgresql://postgres:5432/shecancode}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - JWT_SECRET=${JWT_SECRET:-ZmFrZVN1cGVyU2V5Rm9yRGVtby0xMjM0NTY3ODkw}
      - JWT_EXP_MINUTES=${JWT_EXP_MINUTES:-240}
      - LEAVE_SERVICE_PORT=${LEAVE_SERVICE_PORT:-8080}
    depends_on:
      - postgres
    ports:
      - "${LEAVE_SERVICE_HOST_PORT:-8082}:${LEAVE_SERVICE_PORT:-8080}"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    env_file: .env
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT:-8081}
      - DB_URL=${DB_URL:-jdbc:postgresql://postgres:5432/shecancode}
      - JWT_SECRET=${JWT_SECRET:-ZmFrZVN1cGVyU2V5Rm9yRGVtby0xMjM0NTY3ODkw}
      - JWT_EXP_MINUTES=${JWT_EXP_MINUTES:-240}
    depends_on:
      - postgres
    ports:
      - "${AUTH_SERVICE_HOST_PORT:-8081}:${AUTH_SERVICE_PORT:-8081}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-8088}:80"
    depends_on:
      - auth-service
      - leave-service

volumes:
  pgdata:
